### ISSUE TITLE
1 min timeout when using the plug-in

### ISSUE THREAD

**Issue by jonasgroendahl** [letsbondiway/fastlane-plugin-airwatch_workspaceone#5]
I know this is a long shot but here goes. I'm trying to use this plugin. I have successfully added all the parameters so it stops complaining about the IPA file, missing parameters etc.

Now I get this error message. Any idea why there could be a  timeout after 60 seconds? 

[14:20:15]: Timed out connecting to server

+------+--------------+-------------+
|         fastlane summary          |
+------+--------------+-------------+
| Step | Action       | Time (in s) |
+------+--------------+-------------+
| 💥   | deploy_build | 60          |
+------+--------------+-------------+

```
Traceback (most recent call last):
        37: from /Users/dkjogrpe/.rbenv/versions/2.6.5/bin/fastlane:23:in `<main>'
        36: from /Users/dkjogrpe/.rbenv/versions/2.6.5/bin/fastlane:23:in `load'
        35: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/bin/fastlane:23:in `<top (required)>'
        34: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        33: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        32: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        31: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        30: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        29: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        28: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        27: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        26: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        25: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        24: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        23: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        22: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        21: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        20: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        19: from Fastfile:22:in `block (2 levels) in parsing_binding'
        18: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        17: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        16: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        15: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        14: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        13: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        12: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        11: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-plugin-airwatch_workspaceone-2.4.0/lib/fastlane/plugin/airwatch_workspaceone/actions/deploy_build_action.rb:73:in `run'
        10: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-plugin-airwatch_workspaceone-2.4.0/lib/fastlane/plugin/airwatch_workspaceone/actions/deploy_build_action.rb:146:in `upload_blob'
         9: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
         8: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
         7: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
         6: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:919:in `start'
         5: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
         4: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:945:in `connect'
         3: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
         2: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
         1: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:947:in `open'
/Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/2.6.0/net/http.rb:947:in `initialize': execution expired (Net::OpenTimeout)
        31: from /Users/dkjogrpe/.rbenv/versions/2.6.5/bin/fastlane:23:in `<main>'
        30: from /Users/dkjogrpe/.rbenv/versions/2.6.5/bin/fastlane:23:in `load'
        29: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/bin/fastlane:23:in `<top (required)>'
        28: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
        27: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        26: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
        25: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        24: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        23: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        22: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        21: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        20: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
        19: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        18: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        17: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        16: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        15: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        14: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        13: from Fastfile:22:in `block (2 levels) in parsing_binding'
        12: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        11: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        10: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
         9: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
         8: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
         7: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
         6: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.183.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
         5: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-plugin-airwatch_workspaceone-2.4.0/lib/fastlane/plugin/airwatch_workspaceone/actions/deploy_build_action.rb:73:in `run'
         4: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-plugin-airwatch_workspaceone-2.4.0/lib/fastlane/plugin/airwatch_workspaceone/actions/deploy_build_action.rb:146:in `upload_blob'
         3: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
         2: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
         1: from /Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:651:in `transmit'
/Users/dkjogrpe/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:749:in `rescue in transmit': Timed out connecting to server (RestClient::Exceptions::OpenTimeout)
```

**Comment by jonasgroendahl** [comment]
Would have been nice with some logging to see which api call fails, I didn't have any problems reaching  the api from postman. It couldn't be a vpn or something else right?

**Comment by jonasgroendahl** [comment]
put the wrong url, was confused by the example, my url had console it in
